In [1]:
# multi regression 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

In [3]:
df=pd.read_csv("medical_insurance.csv")

In [5]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [13]:
print(df["region"].unique())
print(df["sex"].unique())
print(df["smoker"].unique())

['southwest' 'southeast' 'northwest' 'northeast']
['female' 'male']
['yes' 'no']

In [11]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [15]:
# we need to do one hot encoding in sex , smoker , region
# for that we need to separate the column
sex = df["sex"]
region = df["region"]
smoker = df["smoker"]

print(sex.shape)
print(region.shape)
print(smoker.shape)

(2772,)
(2772,)
(2772,)

In [33]:
from sklearn.preprocessing import OneHotEncoder

sex_encoder = OneHotEncoder(drop="first", sparse_output=False)
region_encoder = OneHotEncoder(drop="first", sparse_output=False)
smoker_encoder = OneHotEncoder(drop="first", sparse_output=False)


sex_encoded = sex_encoder.fit_transform(sex.to_frame()) # because sklear needs 2d data there fore it sex.to_frame
region_encoded = region_encoder.fit_transform(region.to_frame())
smoker_encoded = smoker_encoder.fit_transform(smoker.to_frame())


print(sex_encoded)
print(region_encoded)
print(smoker_encoded)

[[0.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[1.]
 [0.]
 [0.]
 ...
 [1.]
 [0.]
 [0.]]

In [32]:

print(sex.shape)
sex_2d=(sex.to_frame())
print(sex_2d.shape)

(2772,)
(2772, 1)

In [35]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [41]:
sex_df = pd.DataFrame(sex_encoded,columns=["sex"])
region_df = pd.DataFrame(region_encoded,columns=["region_A","region_B","region_C"])
smoker_df = pd.DataFrame(smoker_encoded,columns=["smoker"])

print(sex_df)
print(region_df)
print(smoker_df)

      sex
0     0.0
1     1.0
2     1.0
3     1.0
4     1.0
...   ...
2767  0.0
2768  0.0
2769  1.0
2770  1.0
2771  1.0

[2772 rows x 1 columns]
      region_A  region_B  region_C
0          0.0       0.0       1.0
1          0.0       1.0       0.0
2          0.0       1.0       0.0
3          1.0       0.0       0.0
4          1.0       0.0       0.0
...        ...       ...       ...
2767       0.0       1.0       0.0
2768       0.0       0.0       1.0
2769       1.0       0.0       0.0
2770       1.0       0.0       0.0
2771       0.0       0.0       1.0

[2772 rows x 3 columns]
      smoker
0        1.0
1        0.0
2        0.0
3        0.0
4        0.0
...      ...
2767     0.0
2768     0.0
2769     1.0
2770     0.0
2771     0.0

[2772 rows x 1 columns]

In [43]:
df["sex_encoded"]=sex_df
df["region_A"]=region_df["region_A"]
df["region_B"]=region_df["region_B"]
df["region_C"]=region_df["region_C"]
df["smoker_encoded"]=smoker_df
df.head(10)

,age,sex,bmi,children,smoker,region,charges,sex_encoded,region_A,region_B,region_C,smoker_encoded
0,19,female,27.900,0,yes,southwest,16884.92400,0.0,0.0,0.0,1.0,1.0
1,18,male,33.770,1,no,southeast,1725.55230,1.0,0.0,1.0,0.0,0.0
2,28,male,33.000,3,no,southeast,4449.46200,1.0,0.0,1.0,0.0,0.0
3,33,male,22.705,0,no,northwest,21984.47061,1.0,1.0,0.0,0.0,0.0
4,32,male,28.880,0,no,northwest,3866.85520,1.0,1.0,0.0,0.0,0.0
5,31,female,25.740,0,no,southeast,3756.62160,0.0,0.0,1.0,0.0,0.0
6,46,female,33.440,1,no,southeast,8240.58960,0.0,0.0,1.0,0.0,0.0
7,37,female,27.740,3,no,northwest,7281.50560,0.0,1.0,0.0,0.0,0.0
8,37,male,29.830,2,no,northeast,6406.41070,1.0,0.0,0.0,0.0,0.0
9,60,female,25.840,0,no,northwest,28923.13692,0.0,1.0,0.0,0.0,0.0

In [48]:
df.drop(columns=["sex","region","smoker"],inplace=True)

In [49]:
df

,age,bmi,children,charges,sex_encoded,region_A,region_B,region_C,smoker_encoded
0,19,27.900,0,16884.92400,0.0,0.0,0.0,1.0,1.0
1,18,33.770,1,1725.55230,1.0,0.0,1.0,0.0,0.0
2,28,33.000,3,4449.46200,1.0,0.0,1.0,0.0,0.0
3,33,22.705,0,21984.47061,1.0,1.0,0.0,0.0,0.0
4,32,28.880,0,3866.85520,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
2767,47,45.320,1,8569.86180,0.0,0.0,1.0,0.0,0.0
2768,21,34.600,0,2020.17700,0.0,0.0,0.0,1.0,0.0
2769,19,26.030,1,16450.89470,1.0,1.0,0.0,0.0,1.0
2770,23,18.715,0,21595.38229,1.0,1.0,0.0,0.0,0.0
2771,54,31.600,0,9850.43200,1.0,0.0,0.0,1.0,0.0

In [51]:
df.isnull().sum()

age               0
bmi               0
children          0
charges           0
sex_encoded       0
region_A          0
region_B          0
region_C          0
smoker_encoded    0
dtype: int64

In [54]:
region_encoder.categories_

[array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]

In [58]:
print(region_encoder.get_feature_names_out())
print(sex_encoder.get_feature_names_out())
print(smoker_encoder.get_feature_names_out())

#output
'''
    ['region_northwest' 'region_southeast' 'region_southwest'] , regio northeast is dropped
    ['sex_male']  , means female is dropped
    ['smoker_yes']   , means NO is droped
    '''

['region_northwest' 'region_southeast' 'region_southwest']
['sex_male']
['smoker_yes']

"\n    ['region_northwest' 'region_southeast' 'region_southwest'] , regio northeast is dropped\n    ['sex_male']  , means female is dropped\n    ['smoker_yes']   , means NO is droped\n    "

| Original region | Encoded columns  |
| --------------- | ---------------- |
| northeast       | 0 0 0 (baseline) |
| northwest       | 1 0 0            |
| southeast       | 0 1 0            |
| southwest       | 0 0 1            |

 0 → female , 
 1 → male

0 → non-smoker ,
1 → smoker

In [59]:
df.head()

,age,bmi,children,charges,sex_encoded,region_A,region_B,region_C,smoker_encoded
0,19,27.900,0,16884.92400,0.0,0.0,0.0,1.0,1.0
1,18,33.770,1,1725.55230,1.0,0.0,1.0,0.0,0.0
2,28,33.000,3,4449.46200,1.0,0.0,1.0,0.0,0.0
3,33,22.705,0,21984.47061,1.0,1.0,0.0,0.0,0.0
4,32,28.880,0,3866.85520,1.0,1.0,0.0,0.0,0.0

In [ ]:
Y = df["charges"]
X = df.drop(columns="charges")
# separaet features and target variable
print(Y)
print(X)

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
2767     8569.86180
2768     2020.17700
2769    16450.89470
2770    21595.38229
2771     9850.43200
Name: charges, Length: 2772, dtype: float64
      age     bmi  children  sex_encoded  region_A  region_B  region_C  \
0      19  27.900         0          0.0       0.0       0.0       1.0
1      18  33.770         1          1.0       0.0       1.0       0.0
2      28  33.000         3          1.0       0.0       1.0       0.0
3      33  22.705         0          1.0       1.0       0.0       0.0
4      32  28.880         0          1.0       1.0       0.0       0.0
...   ...     ...       ...          ...       ...       ...       ...
2767   47  45.320         1          0.0       0.0       1.0       0.0
2768   21  34.600         0          0.0       0.0       0.0       1.0
2769   19  26.030         1          1.0       1.0       0.0       0.0
2770   23  18.715         0          1.0       1.0       0.0       0.0
2771   54  31.600         0          1.0       0.0       0.0       1.0

      smoker_encoded
0                1.0
1                0.0
2                0.0
3                0.0
4                0.0
...              ...
2767             0.0
2768             0.0
2769             1.0
2770             0.0
2771             0.0

[2772 rows x 8 columns]

In [63]:
from sklearn.model_selection import train_test_split

X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [74]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

num_cols = ["age" , "children" ,"bmi"]

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

In [75]:
X_train.head()

,age,bmi,children,sex_encoded,region_A,region_B,region_C,smoker_encoded
1864,-1.314423,1.005365,-0.911834,1.0,0.0,1.0,0.0,0.0
1997,-0.093973,0.669399,0.739073,0.0,0.0,0.0,1.0,0.0
1336,-1.314423,-0.805573,-0.911834,0.0,0.0,0.0,1.0,0.0
655,0.911104,-0.887516,0.739073,0.0,0.0,1.0,0.0,1.0
261,-1.386214,-0.635132,-0.086380,0.0,0.0,1.0,0.0,1.0

In [77]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , mean_squared_error

In [79]:
model = LinearRegression()
model.fit(X_train,Y_train)

y_pred = model.predict(X_test)

In [82]:
print("R² score:", r2_score(Y_test, y_pred))
mse = mean_squared_error(Y_test, y_pred)
print("MSE:", mse)
rmse = np.sqrt(mse)
print("RMSE:", rmse)

R² score: 0.73981661775643
MSE: 39933194.54805148
RMSE: 6319.27167860755